# Generated by Django 2.2.16 on 2021-04-06 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_expiration_date', models.DurationField(default=datetime.timedelta(seconds=180), help_text=' QR код будет недействителен при истечений срока активности', verbose_name='Срок активности QR кода')),
                ('is_service_active', models.BooleanField(default=True, help_text='Убрав галочку, вы можете отключить сервис', verbose_name='Статус сервиса')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
