# Generated by Django 2.2.16 on 2021-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(max_length=15, verbose_name='Версия для android приложения')),
                ('android_force_update', models.BooleanField(default=False, verbose_name='Принудительное обновление(Вкл/Выкл)')),
                ('ios_version', models.CharField(max_length=15, verbose_name='Версия для ios приложения')),
                ('ios_force_update', models.BooleanField(default=False, verbose_name='Принудительное обновление(Вкл/Выкл)')),
            ],
            options={
                'verbose_name': 'Версия мобильного приложения',
                'verbose_name_plural': 'Версии мобильного приложения',
            },
        ),
    ]
