# Generated by Django 2.2.16 on 2021-04-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='ios_build_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Build версия для ios приложения'),
            preserve_default=False,
        ),
    ]
