# Generated by Django 2.2.16 on 2021-05-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_appversion_ios_build_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='ios_build_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Build версия для ios приложения'),
        ),
    ]
