# Generated by Django 2.2.16 on 2021-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='confirmation code'),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmation date'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registration_finish',
            field=models.BooleanField(default=False, verbose_name='is_registration_finish'),
        ),
        migrations.AddField(
            model_name='user',
            name='tmp_phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Временный телефон'),
        ),
    ]
