# Generated by Django 2.2.16 on 2021-04-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210402_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_old_phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='is old phone confirmed'),
        ),
    ]
