# Generated by Django 2.2.16 on 2021-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_old_phone_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_1C_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальный 1С код пользователя'),
        ),
    ]
