# Generated by Django 2.2.16 on 2021-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_user_1c_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, user_1C_code=None), fields=('user_1C_code',), name='unique_user_1C_code_exp_null'),
        ),
    ]
