# Generated by Django 2.2.16 on 2021-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210527_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discount',
            field=models.CharField(max_length=20, verbose_name='Скидка'),
        ),
    ]
