# Generated by Django 2.2 on 2021-03-29 07:58

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок баннера')),
                ('image', models.ImageField(upload_to=core.utils.generate_filename, verbose_name='Фото баннера')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннера',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(choices=[('email-icon', 'Иконка почты'), ('instagram-icon', 'Иконка instagram'), ('facebook-icon', 'Иконка facebook'), ('website-icon', 'Иконка веб-сайта')], default='website-icon', max_length=20, verbose_name='Тип иконки')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок ссылки')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ProgramCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок программы лояльности')),
                ('description', models.TextField(verbose_name='Текст программы лояльности')),
            ],
            options={
                'verbose_name': 'Программа лояльности',
                'verbose_name_plural': 'Программы лояльности',
            },
        ),
        migrations.CreateModel(
            name='PromotionAndNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('information_type', models.CharField(choices=[('news', 'Новость'), ('promotion', 'Акция')], default='news', max_length=15)),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Текст программы лояльности')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный(Вкл/Выкл)')),
            ],
            options={
                'verbose_name': 'Акция и новость',
                'verbose_name_plural': 'Акции и новости',
            },
        ),
        migrations.CreateModel(
            name='PromotionAndNewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.generate_filename, verbose_name='Фото новости или акции')),
                ('is_main', models.BooleanField(default=False, verbose_name='Превью(Вкл/Выкл)')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='info.PromotionAndNews')),
            ],
            options={
                'verbose_name': 'Фотография для акции/новости',
                'verbose_name_plural': 'Фотографии для акций/новости',
            },
        ),
    ]
