# Generated by Django 2.2 on 2021-03-29 08:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcondition',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст программы лояльности'),
        ),
        migrations.AlterField(
            model_name='promotionandnews',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст программы лояльности'),
        ),
        migrations.AlterField(
            model_name='promotionandnews',
            name='information_type',
            field=models.CharField(choices=[('news', 'Новость'), ('promotion', 'Акция')], default='news', max_length=15, verbose_name='Тип записи'),
        ),
    ]
