# Generated by Django 2.2.16 on 2021-03-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210329_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionandnews',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
