# Generated by Django 2.2.16 on 2021-04-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210331_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionandnews',
            options={'ordering': ['-created_at'], 'verbose_name': 'Акция и новость', 'verbose_name_plural': 'Акции и новости'},
        ),
        migrations.AlterModelOptions(
            name='promotionandnewsimage',
            options={'ordering': ['-is_main'], 'verbose_name': 'Фотография для акции/новости', 'verbose_name_plural': 'Фотографии для акций/новости'},
        ),
    ]
