# Generated by Django 2.2.16 on 2021-04-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210406_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionandnews',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
