# Generated by Django 2.2.16 on 2021-04-09 04:33

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20210408_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now, verbose_name='Описание баннера'),
            preserve_default=False,
        ),
    ]
