# Generated by Django 2.2.16 on 2021-04-28 06:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionandnews',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи'),
        ),
    ]
