# Generated by Django 2.2.16 on 2021-05-06 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20210428_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionandnews',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='promotionandnews',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный(Вкл/Выкл)'),
        ),
    ]
