# Generated by Django 2.2.16 on 2021-04-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20210415_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='accrued_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Начислено бонусов'),
        ),
        migrations.AlterField(
            model_name='check',
            name='bonus_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Оплачено бонусами'),
        ),
        migrations.AlterField(
            model_name='check',
            name='money_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Оплачено деньгами'),
        ),
        migrations.AlterField(
            model_name='check',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='check',
            name='withdrawn_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Снято бонусов (Возврат)'),
        ),
    ]
