# Generated by Django 2.2.16 on 2021-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_auto_20210426_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты долга'),
        ),
        migrations.AddField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('accrued', 'Начислено'), ('withdrawn', 'Снято'), ('accrued_and_withdrawn', 'Начислено и снято'), ('on_credit', 'В долг')], default='accrued', max_length=10, verbose_name='Статус чека'),
            preserve_default=False,
        ),
    ]
