# Generated by Django 2.2.16 on 2021-05-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20210429_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='balance_owed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Остаток долга'),
        ),
        migrations.AddField(
            model_name='check',
            name='is_on_credit',
            field=models.BooleanField(default=False, verbose_name='В долг'),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('accrued', 'Начислено'), ('withdrawn', 'Снято'), ('accrued_and_withdrawn', 'Начислено и снято')], max_length=10, verbose_name='Статус чека'),
        ),
    ]
