# Generated by Django 2.2.16 on 2021-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_auto_20210503_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('accrued', 'Начислено'), ('withdrawn', 'Снято'), ('accrued_and_withdrawn', 'Начислено и снято')], max_length=25, verbose_name='Статус чека'),
        ),
    ]
