# Generated by Django 2.2.16 on 2021-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная?'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='end_work',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец рабочего времени'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='start_work',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рабочего времени'),
        ),
        migrations.AlterField(
            model_name='filialimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная?'),
        ),
        migrations.AlterField(
            model_name='filialphone',
            name='is_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Номер Whatsapp?'),
        ),
    ]
