# Generated by Django 2.2.16 on 2021-03-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20210329_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='description',
        ),
    ]
