# Generated by Django 2.2.16 on 2021-04-01 07:21

from django.db import migrations
import django_2gis_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_filial_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandimage',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='link',
        ),
        migrations.AlterField(
            model_name='filial',
            name='geolocation',
            field=django_2gis_maps.fields.GeoLocationField(verbose_name='Геолокация'),
        ),
    ]
