# Generated by Django 2.2.16 on 2021-04-05 11:40

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20210401_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='logo.jpeg', upload_to=core.utils.generate_filename, verbose_name='Лого'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
