# Generated by Django 2.2.16 on 2021-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_auto_20210405_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['position'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AddField(
            model_name='filial',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='№'),
        ),
    ]
