# Generated by Django 2.2.16 on 2021-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_auto_20210426_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['position'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AddField(
            model_name='brand',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='№'),
        ),
    ]
