# Generated by Django 2.2.16 on 2021-06-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_auto_20210512_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='end_work',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='is_around_the_clock',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='start_work',
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ'), (7, 'ВС')], verbose_name='День недели')),
                ('start_work', models.TimeField(blank=True, null=True, verbose_name='Начало рабочего времени')),
                ('end_work', models.TimeField(blank=True, null=True, verbose_name='Конец рабочего времени')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_time', to='brand.Filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'ordering': ['day'],
                'unique_together': {('day', 'filial')},
            },
        ),
    ]
