# Generated by Django 2.2.16 on 2021-04-21 09:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('notice_type', models.CharField(choices=[('bonus_accrued', 'Начислено бонусов'), ('bonus_paid', 'Снято бонусов'), ('bonus_withdraw', 'Снято бонусов неактивных'), ('promotion', 'Акции'), ('news', 'Новости')], max_length=25, verbose_name='Тип')),
                ('linked_object_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='ID связанного объекта')),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Тело')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
