# Generated by Django 2.2.16 on 2021-04-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20210428_1228'),
        ('check', '0003_auto_20210426_1106'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='linked_object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='linked_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='info.PromotionAndNews', verbose_name='Новость или Акция'),
        ),
        migrations.AddField(
            model_name='notification',
            name='linked_check',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='check.Check', verbose_name='Чек'),
        ),
    ]
