# Generated by Django 2.2.16 on 2021-04-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210428_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='linked_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='info.PromotionAndNews', verbose_name='Новость или Акция'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='linked_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='check.Check', verbose_name='Чек'),
        ),
    ]
