# Generated by Django 2.2.16 on 2021-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210428_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notice_type',
            field=models.CharField(choices=[('accrued', 'Начислено бонусов'), ('withdrawn', 'Снято бонусов'), ('accrued_and_withdrawn', 'Начислено и снято'), ('promotion', 'Акции'), ('news', 'Новости')], max_length=25, verbose_name='Тип'),
        ),
    ]
