# Generated by Django 2.2.16 on 2021-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210504_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_on_credit',
            field=models.BooleanField(default=False, verbose_name='В долг?'),
        ),
    ]
